server:
  port: 8082

spring:
  application:
    name: elkan-api-produtos

  data:
    mongodb:
      uri: mongodb://localhost:27017/elkan_produtos_db

management:
  endpoints:
    web:
      exposure:
        include: health,info

